	include	INCLUDE\header.inc
	include	INCLUDE\strathdr.inc
	include	EXT\gstrats.ext
	include	EXT\gcstrats.ext
	include	EXT\gistrats.ext
	include	EXT\gastrats.ext
	include	EXT\expstrat.ext
	include	EXT\windows.ext
	include	EXT\ga2strats.ext
	include	EXT\dstrats.ext
	include	EXT\bootnmi.ext
	include	EXT\gstrats2.ext
	include	EXT\continue.ext
	include	EXT\planets.ext
	include	EXT\ramstuff.ext
	bank	40
	incfile	ASM\pstrats.asm
	incfile	ASM\pistrats.asm
	incfile	ASM\pcstrats.asm
	bankend	40

	bank	41
	incfile	ASM\gb2strats.asm
	incfile	ASM\strings.asm
	bankend	41
	include	INCLUDE\tail.inc


